---

- name: Install dependencies
  hosts: all

  pre_tasks:
  - name: Update package cache
    package:
      name: epel-release
      update_cache: yes
    changed_when: no
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: Install dependencies
    package: 
      name: python-cryptography, pyOpenSSL, java-latest-openjdk, openssh
      update_cache: yes

...