---

- name: Generate test certificate and private key
  hosts: all

  tasks:
  - name: Create certs dirs
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: 0755
      owner: '{{ tls_keystore_owner }}'
      group: '{{ tls_keystore_owner }}'
    loop:
    - '{{ tls_cacerts_path }}'
    - '{{ tls_certs_path }}'
    - '{{ tls_keys_path }}'

  - name: Generate an encrypted private key
    community.crypto.openssl_privatekey:
      path: '{{ tls_key }}'

  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: '{{ tls_certs_path }}/{{ ansible_fqdn }}.csr'
      privatekey_path: '{{ tls_key }}'
      common_name: '{{ ansible_fqdn }}'

  - name: Generate a Self Signed OpenSSL certificate
    community.crypto.x509_certificate:
      path: '{{ tls_cert }}'
      privatekey_path: '{{ tls_key }}'
      csr_path: '{{ tls_certs_path }}/{{ ansible_fqdn }}.csr'
      provider: selfsigned

  - name: CA | Generate an encrypted private key
    community.crypto.openssl_privatekey_pipe:
      passphrase: '{{ tls_key_password }}'
      cipher: auto
    register: cacert_key

  - name: CA | Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr_pipe:
      privatekey_content: '{{ cacert_key.privatekey }}'
      privatekey_passphrase: '{{ tls_key_password }}'
      common_name: '{{ ansible_fqdn }}'
    register: csr

  - name: CA | Generate a Self Signed OpenSSL certificate
    community.crypto.x509_certificate:
      path: '{{ tls_cacert }}'
      privatekey_content: '{{ cacert_key.privatekey }}'
      privatekey_passphrase: '{{ tls_key_password }}'
      csr_content: '{{ csr.csr }}'
      provider: selfsigned

...