---

- name: Manage Keystores
  hosts: all

  tasks:
  - name: Use role encrypt_private_keys
    include_role:
      name: encrypt_private_keys
    loop: '{{ tls_keystores }}'
    loop_control:
      loop_var: outer_item

  - name: Use role keystores
    include_role:
      name: keystores
    loop: '{{ tls_keystores }}'
    loop_control:
      loop_var: outer_item

...