---

dependency:
  name: galaxy
  options:
    role-file: inventories/test/docker/requirements/ansible_requirements.yml

driver:
  name: docker

lint: |
  yamllint playbooks/**
  ansible-lint playbooks/**

platforms:
- name: instance
  image: ${MOLECULE_DISTRO:-ubuntu:20.04}
  privileged: true
  command: ${MOLECULE_COMMAND:-"sleep infinity"}
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    converge: ../../playbooks/tls/keystores.yml
  inventory:
    links:
      group_vars: ../../inventories/test/docker/group_vars/

...