---

name: "deploy"

on:
  push:
    paths:
    - 'test/docker/**'
    - '.github/workflows/deploy.yml'
    - 'molecule/kickstart/**'

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      MOLECULE_COMMAND: ${{ matrix.molecule_distro.command }}
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - { "distro":"centos-7", "command":"/usr/sbin/init" }
          # - { "distro":"centos-8", "command":"/usr/sbin/init" }
          # - { "distro":"ubuntu-18.04", "command":"/lib/systemd/systemd" }
          # - { "distro":"ubuntu-20.04", "command":"/lib/systemd/systemd" }

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          path: ansible-tls-klusters

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        working-directory: ansible-tls-klusters
        run: |
          python -m pip install --upgrade pip
          pip install -r inventories/test/docker/requirements/python_requirements.txt

      - name: Run playbooks
        working-directory: ansible-tls-klusters
        run: |
          molecule test -s kickstart
